### ISSUE TITLE
Use swagger2 for API documentation

### ISSUE THREAD

**Issue by Meldanor** [poma/hotsapi#1]
The API is currently documentated as a website and it lacks of some details and overview.

Swagger is a defacto standard to document RESTful APIs. All documentation is done in one json / yaml file. Also the swagger.json/yaml can be used to generate skeleton for clients / server implementing this API.'

Swagger supplies an online editor http://editor.swagger.io/ to create and edit your file. To display the final result the viewer https://swagger.io/swagger-ui/ can be used to selfhost and try out the API.

All in all a standard documentation via swagger will make using the API much easier to use. Also it will make it easier for the project maintainer when changing or extending the API.

**Comment by poma** [comment]
Great! Didn't know about that. I kinda suck in frontend development so I've just made some markdown and converted it to html.

**Comment by CWSpear** [comment]
I will definitely agree that tools like Swagger would be a great help here. It doesn't have to be Swagger, but I'll 2nd Swagger as being a good call here.

This may also be a good use-case for GraphQL, as it is useful for navigating large datasets and can also help in maximizing bandwidth (really easy on both sides to only transfer the minimum data you need). If that isn't something you're familiar with, tho, it may not be the best route, as it would be a big buy-in.

Either way, I'd be willing to help some with organizing/implementing that if you need assistance.

**Comment by ixidion** [comment]
I'm having a look at https://github.com/OAI/OpenAPI-Specification - It's the successor of Swagger 2.0
The swagger.io editor is OpenAPi 3.0 compatible.

**Comment by ixidion** [comment]
I have created a first draft of the API in Swagger 2.0. OpenAPI (Swagger 3.0) is only a spec without much tool and codegeneration support.

Please check and provide feedback:
https://app.swaggerhub.com/apis/bluemx/hotsapi/0.0.1

**Comment by poma** [comment]
Great! now we need to replace our docs page with this.

You should also include a paragraph about S3 downloads and return object for `POST /replays` method.

**Comment by ixidion** [comment]
Ah I missed the response from the POST method. Will add it tomorrow.

**Comment by ixidion** [comment]
I have created two versions. 
0.0.1 will contain the current API definition as is. POST is now documented.
https://app.swaggerhub.com/apis/bluemx/hotsapi/0.0.1

0.1.0 will be an alternate definition with some issues adressed, e.g. Responsecodes etc.
https://app.swaggerhub.com/apis/bluemx/hotsapi/0.1.0

@poma so you would like to have the Javascript Swagger UI linked on the website (maybe iFrame in first step), sth which looks like this here http://petstore.swagger.io - If yes, I can start to integrate it and send you a pull request.

**Comment by poma** [comment]
Isn't it better to match versions with api endpoints? Let current be v1 and next v2. I intend to design v2 properly so we can start from scratch if needed. v2 is planned for much later, and currently we will try to introduce all changes as non-breaking (maybe as additional endpoints like `/replays/paged`) to v1.

Why do we need an iframe for integration? I'm not familiar with how Swagger UI but that seems a bit weird. But in general yeah we need Swagger UI on docs page.

**Comment by ixidion** [comment]
you are right the iframe is not necessary needed. The following Swager UI [index.html](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html) is a good example how it can be integrated. All in subfolder `dist`is the Swagger UI client, which has to be in the static resources of the project. Swagger file the same. Well, I'm not familiar with PHP/Laravel.

Give the API the version you like. It can be changed according to what you have in mind for longer terms. The style with two dots is [semantic versioning](http://semver.org), the other one I have only seen with Services.

Where should the Swagger file be placed in the code?

**Comment by poma** [comment]
Easy and less preferred way: put resources in `/public/js|css` and modify view `resources/views/docs.blade.php`.

Harder and more preferred way: pull resources with npm. Reference swagger in `package.json`, add as a separate js file in `webpack.mix.js` (because it's pretty heavy), compile everything with elixir and modify `docs.blade.php` accordingly

**Comment by poma** [comment]
In that case don't bother with npm, just put js and css files into public
files and update docs page, I will convert it to npm dependency after.

**Comment by poma** [comment]
While we are waiting for a proper integration I've made a quick dirty one with iframe and static scripts in d26fe93117e09f6a6fc02a8697adee3e0b6977cc so that we can start updating API docs in yaml
