### ISSUE TITLE
Cookie for 'Send a copy to hotslogs'

### ISSUE THREAD

**Issue by Kline-** [poma/hotsapi#105]
Please add a cookie to store the preference of 'Send a copy to hotslogs' option on the web uploader. When I must use the web upload I intend for all my replays to go to both hotsapi and hotslogs, but sometimes forget to select the box until I have already started uploading.

**Comment by tbuehlmann** [comment]
Sounds like a reasonable feature to me.

**Comment by poma** [comment]
fixed
