### ISSUE TITLE
Did something happen to the API?

### ISSUE THREAD

**Issue by Mnfriedl** [poma/hotsapi#113]
When requesting the API for replays, it appears like every replay with a recent `start_date` (like last 3 or 4 months or so) dissapeared. The API is answering with empty arrays of replays, and the older replays are not accessible in the S3 bucket.

[Imgur image with a Postman request](https://i.imgur.com/BeCCD0q.png)

Did something happen to the API?

**Comment by RostumAhady** [comment]
It's a bit weird for me too. The link below returns an empty array of replays. 
https://hotsapi.net/api/v1/replays/paged?page=6&start_date=2018-10-23&end_date=2018-10-29&with_players=true

But if you change the page number to 7 (and any page after that) it will provide the replays. But pages 1 through 6 show up empty.

https://hotsapi.net/api/v1/replays/paged?page=7&start_date=2018-10-23&end_date=2018-10-29&with_players=true

**Comment by Mnfriedl** [comment]
Wow, didn't notice that. It's certainly working strange.

**Comment by poma** [comment]
fixed by removing possibility to filter by `start_date` :)
