### ISSUE TITLE
Feature request: Hero release patch

### ISSUE THREAD

**Issue by martijnhoekstra** [poma/hotsapi#115]
If I want to determine for some replay whether a hero is released or not^1, this is very complicated.

(for those who happen to pass by: the hero has a release date property. Find the highest patch number that has replay on that date, that's the release patch number. This is not equivalent to checking the date on the replay: heroes/patches are not released at 0:00 UTC)

Having a release patch number would make that far easier.

1: and I want to

**Comment by poma** [comment]
this issue should be directed to https://github.com/heroespatchnotes/heroes-talents repo. Once they have this data, I'll import it into my DB.

**Comment by MGatner** [comment]
FYI this is included with https://github.com/poma/hotsapi/pull/124
