### ISSUE TITLE
Results of /replays endpoint not ordered

### ISSUE THREAD

**Issue by fheft** [poma/hotsapi#14]
When using additional parameters to filter the result of the /replays GET endpoint, the API returns results completely unordered.

## Example:
Calling http://hotsapi.net/api/v1/replays?start_date=2017-08-02&min_id=0 to get all replays after August 2, 2017 (starting with ID >= 0)

### Expected result:
List of replays, starting with ID 1, 2, 3, … (all those replays are after the given start_date)

### Current result:
List of replays out of order, ID 364927, 302916, 17017, …

**Comment by poma** [comment]
This is weird, I thought MySQL is supposed to return records ordered by id by default (or rather by insert order, which is the same in our case)
