### ISSUE TITLE
Add metadata to API for pagination

### ISSUE THREAD

**Issue by snowczar** [poma/hotsapi#15]
Add metadata to API for pagination

Expected:
Because we are limited to 100 records per page on the /GET queries, there should be some metadata to help us know how many pages or records there are to help with pagination

Actual:
Without metadata the pagination logic on the client side has to be more complicated.  Because I don't know what the last id is going to be, I have to get the first page, get the last id, then add one and get the next page with min_id=(prevPageLastId+1) and continue until I have less than 100...

Example:

[
  "_metadata": 
  {
      "page": 5,
      "per_page": 100,
      "page_count": 6,
      "total_count": 521,

  },
  "Replays": [
  {
      "id":370026,
      "filename":"3336195043",
      ...
  }]
]

Rational:
Building an app to query the basic info about each replay (not download them) and then provide very basic stats in real time as new replays are uploaded.  Need to be able to query for replays during desired time periods and page through all records for that time period. I.E. "Top 10 Hero Win Ratios in last 24hr for Hero League"

**Comment by poma** [comment]
Agreed

**Comment by ryzngard** [comment]
@poma this seems pretty important (at least to me). I know you put it on the Backlog, do you mind if I try to add this?

**Comment by poma** [comment]
I agree that it is important but I didn't see a way to add this without breaking changes, some users may already rely on result being an array of replays. So before implementing please post how your API will look like. Maybe we can expose it on different url or pass some request parameters to enable pagination functionality.

I think for the first version of API we will just pile on features (with no breaking changes) without worrying too much about elegant design, and after that will release carefully designed API v2.

**Comment by ryzngard** [comment]
Making a separate API sounds like a plan. I'll get a PR going soon to get the discussion going around the design.
