### ISSUE TITLE
Null hero value for (Probably) Kel'Thuzad

### ISSUE THREAD

**Issue by snowczar** [poma/hotsapi#26]
Null hero value for (probably) Kel'Thuzad

Expected:
Replay /Get should return a value for the hero field for each player in the array

Actual:
Seeing null values in recent replays, my guess is this is KT.  May need to look at replay parser and get it more robust for new hero releases.

{
  "id": 1699483,
  "filename": "ac418c8b-533e-5164-7471-a5fbc97e1e81",
  "size": 2196159,
  "game_type": "QuickMatch",
  "game_date": "2017-09-07 03:14:01",
  "game_length": 1165,
  "game_map": "Cursed Hollow",
  "game_version": "2.27.3.57062",
  "region": 2,
  "fingerprint": "ac418c8b-533e-5164-7471-a5fbc97e1e81",
  "url": "http:\/\/hotsapi.s3-website-eu-west-1.amazonaws.com\/ac418c8b-533e-5164-7471-a5fbc97e1e81.StormReplay",
  "players": [
    {
      "battletag": "Rance",
      "hero": "Jaina",
      "hero_level": 10,
      "team": 0,
      "winner": false,
      "blizz_id": 6969354
    },
    {
      "battletag": "Aristarh",
      "hero": "Leoric",
      "hero_level": 6,
      "team": 0,
      "winner": false,
      "blizz_id": 9016907
    },
    {
      "battletag": "NIck",
      "hero": "Murky",
      "hero_level": 6,
      "team": 0,
      "winner": false,
      "blizz_id": 7487954
    },
    {
      "battletag": "SkillzMFG",
      "hero": null,
      "hero_level": 2,
      "team": 0,
      "winner": false,
      "blizz_id": 8689633
    },
    {
      "battletag": "Chuki420",
      "hero": "Rehgar",
      "hero_level": 7,
      "team": 0,
      "winner": false,
      "blizz_id": 8713418
    },
    {
      "battletag": "Equi",
      "hero": "Chromie",
      "hero_level": 7,
      "team": 1,
      "winner": true,
      "blizz_id": 239100
    },
    {
      "battletag": "Tismis",
      "hero": "Li-Ming",
      "hero_level": 17,
      "team": 1,
      "winner": true,
      "blizz_id": 851855
    },
    {
      "battletag": "BelleDuJOur",
      "hero": "Lt. Morales",
      "hero_level": 20,
      "team": 1,
      "winner": true,
      "blizz_id": 785580
    },
    {
      "battletag": "PerdySavvy",
      "hero": null,
      "hero_level": 1,
      "team": 1,
      "winner": true,
      "blizz_id": 11558986
    },
    {
      "battletag": "JohnnyQuest",
      "hero": "Garrosh",
      "hero_level": 5,
      "team": 1,
      "winner": true,
      "blizz_id": 501860
    }
  ]
}

**Comment by poma** [comment]
Oh snap, I've added hourly task to pull translations from hotslogs, but forgot to put laravel scheduler in cron.d. Will rescan broken replays later.

**Comment by poma** [comment]
Rescanned existing replays. Everything should display correctly now.

**Comment by snowczar** [comment]
Seeing this issue again (since about 18 hr ago) with Ana.  Are the tasks running to get the translations?

**Comment by poma** [comment]
Looks like task didn't run for some reason, will investigate. I've ran it manually

**Comment by poma** [comment]
rescanned all replays with null value. still need to investigate why task didn't ran

**Comment by poma** [comment]
Turns out it's a good old "forgot to add a newline at the end of cron file"
