### ISSUE TITLE
Response Header : access-control-allow-origin : *

### ISSUE THREAD

**Issue by drdeteck** [poma/hotsapi#27]
Hey guys, it would be cool if you include 
`access-control-allow-origin : *`
in the response header of your API so Chrome would accept it in the front-end dev 

Right now, we get this error from Chrome :
`Fetch API cannot load http://hotsapi.net/api/v1/replays. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.`

**Comment by poma** [comment]
fixed
