### ISSUE TITLE
Suggestions for display of web uploader result stats?

### ISSUE THREAD

**Issue by ekzor** [poma/hotsapi#29]
I've already got a nearly complete implementation of file upload stats for the web uploader, similar to what the app shows (i.e. Success, Duplicate, TooOld, etc), and will be requesting it be added to the codebase soon. However, I'm wondering if anyone has any preferences for how this data should be displayed on the page? 

I'd prefer to keep the website looking nice and clean as it does currently. The idea I'm currently proceeding with is:
- "[x] out of [y] files" overlaid on the main progress bar
- mousing over the main progress bar reveals a stylized tooltip showing the totals for different upload status results

That way the numbers are available but without taking up any additional space on the page so it stays simple/clean looking.

Anybody have any thoughts or input on this? Would you guys want the upload stats always visible above the file list rather than hidden in a tooltip?

**Comment by snowczar** [comment]
Your idea sounds fine to me.

**Comment by poma** [comment]
I think most users will never find out that there is a tooltip over progress bar. Why not use 2 columns?

![Mockup](https://i.imgur.com/HHHO6zg.png)

**Comment by ekzor** [comment]
@poma True, people might not notice. The stats will never extend as far down as the file listing however, so it might look out of place in that exact spot.

There's some empty space above the overall progress bar to the right of the file selection buttons though, so perhaps I'll find a way to fit it in there (see below). Does that sound alright? Might try to get upload speed and estimated time remaining in there too....

![capture](https://user-images.githubusercontent.com/7154375/30218449-0df19c64-9487-11e7-9f22-a838543f3178.PNG)

**Comment by poma** [comment]
There are at least 8 possible statuses, it will look awkward above the progress bar if this list gets too long. Also overall progress bar can be moved to the same line as upload button as in mockup.

Filenames closer horizontally to their result status are easier to read, although I agree that status list to the side looks kinda weird. I think just make your decision how to do it, we can always revisit it later if someone finds more elegant solution.

For progress bar I think both variations are good but progress to the side looks a bit more familiar to users. If you also think it is better and don't feel too lazy you can change it :)

**Comment by ekzor** [comment]
(crap I hit the close button by accident)

if there is indeed 8 statuses then it might not fit as neatly, you're right. I'll come up with something that fits!

**Comment by ekzor** [comment]
Need to hide the tooltip hover toggle if there are no skipped replays
