### ISSUE TITLE
Return map name and hero name with localization

### ISSUE THREAD

**Issue by MakiseKurisu** [poma/hotsapi#31]
Currently we have to hard code those constants in our program, which is very vulnerable to each new hero/map release. Come sort of universal way to get those names in a single list and provide hero/map id instead of a string for faster processing (like what HotsLogs CSV export does) is very helpful.

**Comment by poma** [comment]
HotsLogs parse and translate hero names just like we do

**Comment by MakiseKurisu** [comment]
Never realize HotsLogs exports those data, so maybe add it to FAQ? Also I'd like to know the request quota. Hitting it several times today while testing my code.

**Comment by ekzor** [comment]
there's a header in the return that shows you the request quota, how much you have remaining and - if you trigger the throttle - when it'll reset. I can look up the actual header names for you soon if you don't find it

**Comment by MakiseKurisu** [comment]
@ekzor those info can be quite useful to put in hotsapi.net/docs cuz i'm a noob to this php stack and i bet there are other ppl who also want to know them.

**Comment by ekzor** [comment]
I'm not super familiar with this PHP stack myself but stumbled on it when I was working on the uploader:

-`X-RateLimit-Limit` tells you the max number of requests you're allowed to make within this application's time period

-`X-RateLimit-Remaining` tells you how many requests you have left within this current time period

-`Retry-After` tells you how many seconds to wait until you try again.

(from https://mattstauffer.co/blog/api-rate-limiting-in-laravel-5-2/) 

hope this is helpful!

**Comment by poma** [comment]
I've added translations API: `GET /heroes/translations` and `GET /maps/translations`. `translations` property is reserved for DB relation so I display translations in `versions` property. If you can suggest a better name for it I will change.

**Comment by MakiseKurisu** [comment]
If `versions` is divided into different language that might be better.

**Comment by poma** [comment]
Can you give an example?

**Comment by poma** [comment]
Found a way to rename array to `translations`. This will be our final model.
