### ISSUE TITLE
A simple python package for hotsapi

### ISSUE THREAD

**Issue by MakiseKurisu** [poma/hotsapi#32]
https://github.com/MakiseKurisu/hotsapi

Just get this done in a few minutes. Might be helpful for other people.

Hoping to get a native implementation for #31 so we can have a usable translation, but not a big deal if you just want to do some data analysis.

**Comment by ekzor** [comment]
cool!

**Comment by tbuehlmann** [comment]
Nice!

I implemented an API client for ruby: [tbuehlmann/hots_api](https://github.com/tbuehlmann/hots_api)
