### ISSUE TITLE
Suggestion: Default path for Mac and Windows

### ISSUE THREAD

**Issue by unwill** [poma/hotsapi#34]
Most people just install the game on default location, and have no clue where the replay files is located (for both PC and MAC).

On the upload page, the path should be listed, and maybe default typed in when pressing the upload file / directory button.

**Comment by poma** [comment]
AFAIK it is not possible to set a default path for upload button (and windows path contains name which we don't know anyway). But we should list default paths on upload page that's for sure.

**Comment by poma** [comment]
For Windows it is `C:\Users\<username>\Documents\Heroes of the Storm\Accounts\<id>\<region>-Hero-1-<id>\Replays\Multiplayer\`

For Mac `~/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/<id>/<region>-Hero-1-<id>/Replays/Multiplayer/`

**Comment by ekzor** [comment]
@poma I can add this info alongside the upload status display update (Issue #29), unless you've already prepared a change?

**Comment by poma** [comment]
I didn't work on this yet
