### ISSUE TITLE
Inefficient query when selecting by battletag

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#35]
`http://hotsapi.net/api/v1/replays?player=Grubby` runs too long, need to investigate

**Comment by poma** [comment]
execution: 20s 67ms, fetching: 23s 254ms

SQL produced 
```
select * from `replays` where exists (select * from `players` where `replays`.`id` = `players`.`replay_id` and `battletag` = 'Grubby') order by `id` asc limit 100;
```

explain:
.|.|.|.|.|.|.|.|.|.
|-|-|-|-|-|-|-|-|-|-|
1 | PRIMARY | replays |  | index |  | PRIMARY | 4 |  | 100 | 100 | Using where
2 | DEPENDENT SUBQUERY | players |  | ref | players_replay_id_foreign,players_battletag_index | players_replay_id_foreign | 4 | hotsapi.replays.id | 10 | 0.49 | Using where

**Comment by ekzor** [comment]
could you rewrite this to use a JOIN rather than a subquery? it might be faster that way. something like this:

```
select * from replays join players on replays.id = players.replay_id where players.battletag = 'Grubby' order by id asc limit 100;
```

(haven't tested this or looked at the db, just based on your query)
