### ISSUE TITLE
Replay with game_map NULL (probably Lost Cavern)

### ISSUE THREAD

**Issue by Err0r404** [poma/hotsapi#36]
Hi,

Just ran into a replay with a NULL game_map, not sure if it's a problem or just a bad replay...

Here is the replay : [http://hotsapi.net/api/v1/replays/18757](http://hotsapi.net/api/v1/replays/18757)

Here are the information :
`{
	"id": 18757,
	"filename": "b0f40e46-54ff-debd-9f9a-67a2413c665a",
	"size": 168221,
	"game_type": "Brawl",
	"game_date": "2017-07-01 06:18:48",
	"game_length": 211,
	"game_map": null,
	"game_version": "2.26.2.55010",
	"region": 2,
	"fingerprint": "b0f40e46-54ff-debd-9f9a-67a2413c665a",
	"url": "http:\/\/hotsapi.s3-website-eu-west-1.amazonaws.com\/b0f40e46-54ff-debd-9f9a-67a2413c665a.StormReplay",
	"players": [{
		"battletag": "BlaxPayne",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 0,
		"winner": true,
		"blizz_id": 1927844
	}, {
		"battletag": "B1gBY",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 0,
		"winner": true,
		"blizz_id": 1087640
	}, {
		"battletag": "Oddy",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 0,
		"winner": true,
		"blizz_id": 957117
	}, {
		"battletag": "Rhenus",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 0,
		"winner": true,
		"blizz_id": 425615
	}, {
		"battletag": "SinBulldozer",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 0,
		"winner": true,
		"blizz_id": 2774831
	}, {
		"battletag": "Ashaerzul",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 1,
		"winner": false,
		"blizz_id": 1673645
	}, {
		"battletag": "Khadgar",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 1,
		"winner": false,
		"blizz_id": 1306425
	}, {
		"battletag": "Time2Play",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 1,
		"winner": false,
		"blizz_id": 1913962
	}, {
		"battletag": "RoelNL",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 1,
		"winner": false,
		"blizz_id": 504907
	}, {
		"battletag": "Q0000",
		"hero": "Stitches",
		"hero_level": 1,
		"team": 1,
		"winner": false,
		"blizz_id": 1504734
	}]
}`

**Comment by poma** [comment]
German translation for pool party was missing a comma: "Ich glaub, es hakt". Likely because hotslogs uses commas to separate translations so it strips them from names.

Fixed now.
