### ISSUE TITLE
replays/{id} additional return values

### ISSUE THREAD

**Issue by FrancoisWiid** [poma/hotsapi#37]
In addition to the current values that are returned from the match id, I would love to see the following so that we don't have to use a very complicated method of getting match data from HOTS Logs.

- Player Stats: Take-downs, deaths, kills, hero damage, siege, healing, XP, etc.
- Player Score % based on role, similar to the HOTS Logs player score %. This might be something already available from the replay file, the % that HOTS use for MVP.
- Hero Talent Picks & Quests
- Objective Stats
- Map Mechanics like stats on bosses, camps, towers, etc.

There are so many metrics from a single match, seeing more and more of these in the replay/id GET would mean that a single REST connection could provide valuable information, very easily.

**Comment by FrancoisWiid** [comment]
It might be better to break this into multiple issues so that additions are added in increments instead of one big issue?

**Comment by poma** [comment]
I'll outline our roadmap in the next reddit post (and will copy it to readme). The short version is this: talents,  bans, and score screen stats will be available as soon as we bring set up additional parsing with Heroes.ReplayParser (will be after mac uploader).

Game event based stats like mercs, objectives, quests are currently not planned. Maybe someone will set up a site that analyzes game events from replays and displays stats about them.

**Comment by juckele** [comment]
I've noticed that replays/{id} gives player lists but replays does not. Is that intended?

**Comment by poma** [comment]
Also there is `with_players` param that allows to include players in response

**Comment by FrancoisWiid** [comment]
Might be a bit off topic, but when you upload to hotslogs, do you get an id back from them? Some how to match their match id with your replay id?

**Comment by poma** [comment]
No, I just get "success"
