### ISSUE TITLE
Search for duplicate : undocumented & not compatible with hotslogs

### ISSUE THREAD

**Issue by sloonz** [poma/hotsapi#38]
Hello,

I implemented hotsapi.net support for HotSUploader (https://github.com/eivindveg/HotSUploader/pull/162). However, duplicate detection does not seems to work.

For duplicate detection, I refered to [this comment](https://github.com/poma/Hotsapi.Uploader/blob/e20099f0c2296fd9e6fd6bdd03c64142d42a4ebe/Hotsapi.Uploader.Common/Analyzer.cs) : 

```
/// <summary>
/// Get unique hash of replay. Compatible with HotsLogs
/// </summary>
/// <param name="replay"></param>
/// <returns></returns>
```

But that doesn’t seems right. I uploaded a replay using HotSUploader (both on hotslogs & hotsapi) ; its fingerprint is be9c026956-eac1-ea29-f5b8-51bfda4d5f77. I then tried to re-upload it ; hotslogs detects the duplication but not hotsapi. 

```
$ curl http://hotsapi.net/api/v1/replays/fingerprints/v2/be9c026956-eac1-ea29-f5b8-51bfda4d5f77
{"exists":false}
```

The corresponding replay on hotsapi.net has id=1981612 and its fingerprint on hotsapi is 9c026956-eac1-29ea-f5b8-51bfda4d5f77.

**Comment by poma** [comment]
Indeed something is not right with fingerprint calculation, I've noticed that too. My function passed on a test replay but looks like it gives different values on other replays. We need to find a but and then I will recalculate hash for my replay base.

**Comment by sloonz** [comment]
Don’t have a C# compiler on my machine right now. Could you give me the value of `str` and `md5` for the replay above, so I can compare with HotSUploader values ?

**Comment by poma** [comment]
Str `95606910982877362799800188292427899481839100717881012303611349768114218951582806235`, md5 `9c026956-eac1-29ea-f5b8-51bfda4d5f77`

**Comment by sloonz** [comment]
OK. Both string and MD5 are the same. And it’s obvious in retrospect : hotslog_uuid = "be" + md5. MD5 is 16 bytes, hotsapi UUID is 16 bytes, hotslog UUID is 17 bytes. Gotta figure where this extra bytes comes from.

**Comment by sloonz** [comment]
I’m an idiot. be is the word "be" from "Calculated matchId to be" + uuid. Notice the missing space in the debug string :)

**Comment by sloonz** [comment]
Finally got it. Reordering of bytes is not the same, compare : 

```
9c026956-eac1-ea29-f5b8-51bfda4d5f77
9c026956-eac1-29ea-f5b8-51bfda4d5f77
```

Hotsapi:

```
$guid_byte_order = [3, 2, 1, 0, 5, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
```

Hotslogs:

```
        return new byte[]{
                hashed[3],
                hashed[2],
                hashed[1],
                hashed[0],

                hashed[5],
                hashed[4],
                hashed[7],
                hashed[6],
                hashed[8],
                hashed[9],
                hashed[10],
                hashed[11],
                hashed[12],
                hashed[13],
                hashed[14],
                hashed[15],
        };
```

6 and 7 are swapped

**Comment by poma** [comment]
Hmm, that's weird. HotsLogs uses C# as a backend and this is Microsoft byte sequence (in C# I pass byte array directly to guid constructor like so `new Guid(md5(stringBytes)).ToString()`)

I still see something weird here. When I check replays from my DB on HotsLogs I still get "Success" instead of "Duplicate" even with bytes swapped. Can you check if duplicate detection with HotsLogs is working?

**Comment by sloonz** [comment]
Yes, it seems to be working. 

```
$ curl 'https://www.hotslogs.com/UploadFile?Source=HotSLogsUploaderFX&ReplayHash=9c026956-eac1-ea29-f5b8-51bfda4d5f77'
Duplicate
```

HotSUploader application logs : 

```
2017-09-14 11:43:54.049  INFO 12399 --- [pool-3-thread-1] n.e.h.p.hotslogs.HotsLogsProvider        : Calculated matchId to be9c026956-eac1-ea29-f5b8-51bfda4d5f77
2017-09-14 11:43:54.049  INFO 12399 --- [pool-3-thread-1] n.e.h.utils.SimpleHttpClient             : Opening connection to https://www.hotslogs.com/UploadFile?Source=HotSLogsUploaderFX&ReplayHash=9c026956-eac1-ea29-f5b8-51bfda4d5f77
2017-09-14 11:43:54.229  INFO 12399 --- [pool-3-thread-1] n.e.h.concurrent.tasks.UploadTask        : Parsed preStatus reported no need to upload test.StormReplay for provider HotSLogs.com
2017-09-14 11:43:54.241  INFO 12399 --- [lication Thread] n.e.h.services.UploaderService           : Resolved status UPLOADED for test.StormReplay
```

**Comment by poma** [comment]
Yea looks like I've tested by swapping wrong bytes. All seems to be working fine.

I'll create a new `/replays/fingerprints/v3` endpoint for new hashes and leave v2 for compatibility.

**Comment by poma** [comment]
v3 check is on production, pls test

**Comment by sloonz** [comment]
Seems to be working : 

```
2017-09-14 12:14:38.507  INFO 14331 --- [pool-3-thread-1] n.e.h.concurrent.tasks.UploadTask        : Parsed preStatus reported no need to upload test.StormReplay for provider HotsApi
```
