### ISSUE TITLE
GET replays/fingerprint/{fingerprint} - Lookup by fingerprint

### ISSUE THREAD

**Issue by jsuereth** [poma/hotsapi#53]
This may actually be a red herring feature request.  I'm working on a "custom tournament setup" website, where I'm planning to have teams post results via replay files and use hotsapi to store replays in a way that is usable by the community you're growing.

What I'd like is the ability to check if a replay has already been uploaded (by, e.g. an automatic uploader or other utility) before sending you all those bits and wasting resources.    

SO, can I take the MD5 or SHA1 of the replay file and just send you a "fingerprint"?   

Also, could you update the docs to share what fingerprint means?

**Comment by jsuereth** [comment]
Ok, also, checking out the uploader code, I'm aware of:

{ApiEndpoint}/replays/fingerprints/v3/{fingerprint}

What I'm asking, though, is for the fingerprint algorithm to be publicized in a way I can do this from Scala, python, or whatever language my processing pipeline is in.

Thanks!

**Comment by poma** [comment]
Replay file for the same will contain different bytes for each player (for example different chat messages for each team) so you can't just take file's md5. Replay hash is calculated as follows: 

1. get blizzard id for every player (numeric ones)
2. sort as integers ascending
3. concatenate them
4. append replay's random value
5. get md5
6. and then some reorder resulting bytes as `[3, 2, 1, 0, 5, 4, 7, 6, 8, 9, 10, 11, 12, 13, 14, 15]` to be compatible with hotslogs' hash

Later I may introduce API endpoint that does step 6 for you but other steps are still required to calculate replay's hash.

**Comment by jsuereth** [comment]
Would you be ok lifting the fingerprints URL endpoints into the publicly documented/supported ones? 

If so, great!    If not, feel free to close this and I'll just upload the replays each time for V1.

**Comment by poma** [comment]
Yes I'll publish hash descriptions later. All versions before v3 are deprecated btw and will be removed. Version 3 will become public and is compatible with hotslogs replay hashes. I'll also make an additional endpoint to accept plain md5 without byte reorder and dashes.

**Comment by ekzor** [comment]
just a quick note @jsuereth: if your tournament games are custom games, hotsapi won't accept them.

(@poma correct me if i'm wrong)

**Comment by jsuereth** [comment]
Awesome!  thank you very much.

**Comment by jsuereth** [comment]
@poma @ekzor Would be good to confirm the custom game limitation. I had assumed since hotsdata can upload to hotsapi, that you also allowed custom games.  If not, I'll have to wire in my own parser + uploading framework....

**Comment by poma** [comment]
Yes currently hotsapi doesn't accept custom games. We will likely start accepting them later when I'll have a clear understanding of use case for them. Custom game stats are not useful without any additional metadata, they may contain all kinds of random stuff.
