### ISSUE TITLE
replays/paged endpoint taking very long

### ISSUE THREAD

**Issue by tbuehlmann** [poma/hotsapi#54]
Requests to https://hotsapi.net/api/v1/replays/paged take a very long time and often time out. Requests to https://hotsapi.net/api/v1/replays are fast as usual (besides #35). I guess there's something wonky with the pagination.

**Comment by fheft** [comment]
I found the 'total' number of replays quite useful as it allows for some meaningful management of EC2 instances (i.e. "over 10,000 unparsed replays? then start an instance!").
Hoping we can find a way to re-enable this info somehow.

**Comment by snowczar** [comment]
I am not seeing the "page_count" and "total" values as expected in the /paged documentation currently.  Is it not implemented yet, temporarily disabled, or defect?  

Example: http://hotsapi.net/api/v1/replays/paged?start_date=2017-09-26
{
  "per_page": 100,
  "page": 1,
  "replays": [
    {
      "id": 1307831,
      "filename": "f6f30a75-b6bb-c948-763b-67018f4c465d",
      "size": 496490,....

**Comment by poma** [comment]
they are temporarily disabled because of big performance impact

**Comment by tbuehlmann** [comment]
Adding the part I only wrote on Gitter:

We can speed up pagination using page numbers using a join: 

    mysql> SELECT COUNT(*) FROM hotsapi.replays;
    +----------+
    | COUNT(*) |
    +----------+
    |  3000000 |
    +----------+
    1 row in set (0.36 sec)

    mysql> SELECT * FROM hotsapi.replays ORDER BY id ASC LIMIT 2899900, 100;
    …
    100 rows in set (1.25 sec)

    mysql> SELECT * FROM hotsapi.replays JOIN (SELECT id FROM hotsapi.replays ORDER BY id ASC LIMIT 2899900, 100) AS t ON t.id = replays.id;
    …
    100 rows in set (0.55 sec)

This is because of early/late row lookup and happens for big tables and big offsets.

**Comment by ekzor** [comment]
@tbuehlmann if you run your queries in reverse order, do the times change? I'm wondering if the database driver is caching the result for the first SELECT query and using it in the second one.

**Comment by tbuehlmann** [comment]
Can't check right now, but I assume there's no caching involved. As said, this is a regular thing in mysql world. See:

- https://explainextended.com/2009/10/23/mysql-order-by-limit-performance-late-row-lookups/
- https://explainextended.com/2011/02/11/late-row-lookups-innodb/

**Comment by mjibson** [comment]
Due to the slowness of the offset parameter in the limit clause to get paging to work, it may be good to consider removing the paged API altogether. The initial, ID-based one, allows the database to use its index and jump to the appropriate start record instead of scan all X rows to get to the correct page.

**Comment by tbuehlmann** [comment]
Pagination time is fixable, as pasted above. So I'm for either fixing it or removing it completely as @mjibson suggested. As long as we can't order records by a different attributes than id, paginating doesn't make sense to me anyway.

**Comment by poma** [comment]
fixed by removing this endpoint
