### ISSUE TITLE
What are the different gametypes?

### ISSUE THREAD

**Issue by crorella** [poma/hotsapi#56]
Hi,

I couldn't find this info on the API documentation. I'm interested on everything but Brawls, VS AI and Custom games. Where can I get the different gametype values present in the replay repo?

Thanks!

**Comment by poma** [comment]
[ParserService.php#L30](https://github.com/poma/hotsapi/blob/master/app/Services/ParserService.php#L30)

QuickMatch, UnrankedDraft, HeroLeague, TeamLeague
