### ISSUE TITLE
Parse full Battletags

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#6]

**Comment by tobz** [comment]
This seems unlikely without a fork of heroprotocol or writing a wrapper application for Heroes.ReplayParser.

Do you have any deep thoughts about switch from heroprotocol to Heroes.ReplayParser?  We could obviously make it run on OS X/Linux with .NET Core.  It would at least unify the uploader and backend in a small way.

**Comment by poma** [comment]
Yes, to implement this we will need to parse battlelobby file manually.

Originally I thought that I want to implement parsing in 2 stages: first read the information required to decide replay status (ai, duplicates, etc.) using a reliable official parser and then use Heroes.ReplayParser in a queue worker to extract additional information because it formats replay data in a much more user friendly way.

But now I think that maybe it would be easier to use ReplayParser for everything. Especially since I'm going to convert my fork to .NetStandard for Mac uploader anyway.

**Comment by tobz** [comment]
I agree: I think Heroes.ReplayParser is the best available choice.

Alternatively, you could also push all of this to the uploader.  It makes the API a very thin layer for storing the metadata + storing the replay, but it avoids needing to set up a queueing infrastructure or writing a new console app to shell out to.

Either way, I'd love to help on this if you can give some direction. :)
