### ISSUE TITLE
Get replays with player= is returning unexpected records

### ISSUE THREAD

**Issue by snowczar** [poma/hotsapi#61]
Get replays with player= is returning unexpected records

The following GET request:
http://hotsapi.net/api/v1/replays?player=Doombob&start_date=2017-09-28
should only be returning 3 matches from from today, but instead it is returning many that clearly do not match.

**Comment by poma** [comment]
it is temporarily disabled for performance reasons

**Comment by Cruglk** [comment]
Здравствуйте, Роман!

Если не ошибаюсь, Вы понимаете русский язык, и сообщение на русском языке будет рассмотрено.

Возник идентичный проблемный момент с получением информации о конкретном игроке. Хотел у Вас запросить уточнение - будут ли произведены изменения в ближайшее время по данной ситуации или не планируется.

Возникла идея по реализации вывода информации об актуальных результатах за день (кол-во побед/поражений), но hotsapi сейчас этого сделать не позволит (по ситуации выше). 

Т.е. планируется выполнять запрос к hotsapi через скрипт - брать информацию о результатах игрока за промежуток времени - все это обрабатывать и выводить инфо. 

С hotslog парсить через curl - 500 матчей  (когда необходимо не более 50 за сутки) приходиться загружать каждые полчаса, Ben (разработчик hotslog) указывает, что API допиливать не планирует, и что стоит обратить внимание на hotsapi.

Понимаю, нагрузка у Вас большая (много работы предстоит и уже "висит"), потому не о чем не прошу, лишь желал уточнить о ситуации в целом, планируется ли вернуть поиск реплеев по игроку или не стоит ожидать этого в ближайший месяц, например.

Спасибо за Ваш труд!

**Comment by poma** [comment]
Yes I plan to enable it as soon as we optimize SQL query to complete in a reasonable time. A simple `where id in (...)` seems to perform 200x faster than laravel's default `where exists` so optimization is certainly possible we just need to code it.

>С hotslog парсить через curl - 500 матчей (когда необходимо не более 50 за сутки) приходиться загружать каждые полчаса

Didn't understand this part

**Comment by poma** [comment]
fixed
