### ISSUE TITLE
[WIP] Possible replacement for heroprotocol/Heroes.ReplayParser.

### ISSUE THREAD

**Issue by tobz** [poma/hotsapi#63]
Heyo!

So, I've been working on a replacement for Heroes.ReplayParser that is both fast and feature compatible.  As of right now, it can provide all of the information that is currently being stored/returned by the API.  I'm still working towards making it effectively feature complete with Heroes.ReplayParser.  This isn't a matter of if, but when.

As far as speed goes, it is *very* fast.

Testing with a replay from August 30th (so a recent replay, with all the new tracking data, etc):

Heroes.ReplayParser: 1550ms
heroprotocol (same params that you use): 160ms
rs-storm-parser[1] (my project): 8ms

Yes, you've read that correctly. :D These are also release builds where possible.

Now, as I mentioned, it's not parsing everything yet, and I'm also testing these purely on OS X... so Heroes.ReplayParser might be a good chunk faster on Windows/Linux.

I've added timings to Heroes.ReplayParser to try and figure out how long each chunk of parsing takes.  Based on the things my parser currently parses, and figuring out the total time it takes just for those pieces in Heroes.ReplayParser, my parser is still 10x faster.

So, the wholeee reason I'm working on this and am here in this issue is that I knew you have limited resources and server-side processing power was a concern for doing deeper analysis.

My questions to you are:
- does being able to do the server-side parsing efficiently interest you?
- if so, are you interested in possibly using this library?
- if so, what would be the most important thing to you feature wise? (battletags, talent picks, etc etc)

Curious to hear your thought!

[1] - https://github.com/nuclearfurnace/rs-storm-parser

**Comment by poma** [comment]
I have a couple of questions on how you compare performance. Currently hotsapi uses 2 stage parsing. First it looks only in header/details/attributeevents parts of the archive to retrieve basic data: heroprotocol on server and a fork of Heroes.ReplayParser in uploader (see [this](https://github.com/poma/Heroes.ReplayParser/commit/c1303788a6fc77cedb43b2775336773476f5dcca) commit). Then server side extracts additional data with ReplayParser, you can see an example of a fully parsed replay [here](http://hotsapi.net/api/v1/replays/1), it includes talents, scores, bans, and full battletags.

* did you measure performance of all 3 parsers with or without unpacking gameevents?
* did you measure performance on a single or multiple CPU cores? I can run multiple parsers concurrently so the fact that heroprotocol and ReplayParser are single threaded doesn't matter
* does your parser have a good support of old client versions? ReplayParser handles a lot of special cases in older patches
* how easy it is to update your parser for new client versions?
* does your parser support additional data that I've mentioned above

**Comment by poma** [comment]
After some testing this doesn't look right to me. Here's what I get on a c4.large:

```
$ time heroprotocol --json --trackerevents --gameevents --messageevents --attributeevents --header --details --initdata bd1449e2-4687-06f8-7761-8b2a4b3ed3df.StormReplay > /dev/null
14.66s user 0.06s system 99% cpu 14.781 total
$ time heroprotocol --json --gameevents bd1449e2-4687-06f8-7761-8b2a4b3ed3df.StormReplay > /dev/null
14.28s user 0.01s system 99% cpu 14.356 total
$ time heroprotocol --json --attributeevents --header --details --initdata bd1449e2-4687-06f8-7761-8b2a4b3ed3df.StormReplay > /dev/null
0.07s user 0.00s system 99% cpu 0.069 total
$ time hotsapi-parser bd1449e2-4687-06f8-7761-8b2a4b3ed3df.StormReplay > /dev/null #this is ReplayParser wrapper
2.42s user 0.14s system 102% cpu 2.485 total
```

heroprotocol is super slow, even when parsing only gameevents (required for talents and other stuff) it takes 15(!) seconds. But it is fast enough for extracting headers for step 1 parsing, 0.07s
My .Net Core port of ReplayParser takes similar to what you've stated (probably you have a faster CPU). I'll do some performance profiling later, maybe there are some slow functions that can be improved, but I think Barrett already removed all major bottlenecks.

**Comment by tobz** [comment]
(I'm going to break this up into multiple comments so I can focus on each section)

## Performance

When I was measuring performance, as I noted, my parser was only parsing the metadata, details, and init.  This is equivalent to the list of players (no battletag, no talents), map, game mode, game length, random value, and other small bits of information.  With my parser, this takes roughly 8ms.

Comparatively speaking, I ran both heroprotocol and Heroes.ReplayParser in their "normal" modes:
- for heroprotocol, I was running it with the exact same flags you ran it with for hotsapi
- for Heroes.ReplayParser, it was just parsing everything, like it normally does

However, for Heroes.ReplayParser, I added timing outputs for individual sections.  When you take the processing time for the sections in Heroes.ReplayParser that my parser current implements (metadata, or the MPQ "user data", as well as "details" and "init"), my parser is still 10x faster than Heroes.ReplayParser, which took roughly 80ms to read/process the same data that my parser can read/process in 8ms.

My parser is currently single-threaded.  I don't really have any plans to try and multi-thread it because it's very fast as is, and as you mentioned, running multiple processes is a valid concurrency strategy.

**Comment by poma** [comment]
For headers I think heroprotocol is fast enough, we don't really need more performance there, it's worth to continue using it for reliability of uploads because it is an official parser and is updated automatically for each new HotS client release.

It's interesting to see if you manage to significantly improve performance of unpacking gameevents compared to ReplayParser, this can be very useful.

**Comment by tobz** [comment]
## Compatibility

My parser library is effectively a port of Heroes.ReplayParser to Rust.  I'm trying to stay faithful to not only the behavior but the naming conventions of Heroes.ReplayParser, such as the name of fields in the output, etc.

The biggest deviations are changing the layout and available fields on some structs to better fit the constraints and ergonomics of Rust.  By and large, though, it's a port.

Whenever I see things like this in Heroes.ReplayParser:

```
// I haven't tested the following code on replays before build 39595 (End of 2015)
if (replay.ReplayBuild < 39595)
    return;
```

They get included in rs-storm-parser, including the code comments.

As far as updating rs-storm-parser for new client versions, it's just as easy as updating Heroes.ReplayParser... in the sense of, someone just needs to update it. :)

While I don't have any older builds to test some of the aforementioned special cases, I do plan on attempting to generate a corpus of known replay files which includes good and bad replays, on different builds, for automated testing continuously.

**Comment by tobz** [comment]
## Feature Parity

Right now, rs-storm-parser lacks attribute parsing, tracker and game event parsing, and battlelobby parsing.  Almost all of the groundwork for these is done, though, so it's mostly a matter of porting the existing code from Heroes.ReplayParser.  This part is relatively fast.

**Comment by poma** [comment]
Processing all current replays with ReplayParser should take around >2000 cpu*hours +50% of that for various overheads, which is ~$30 on r4.large spot instances. And again if we decide to extract more data in the future. A significant sum for the current donation amount but still within budget.  The cost of maintaining parsing for incoming replay flow is proportional to that, not very expensive.

Since ReplayParser is already maintained by Barrett and I'm familiar with it and C# in general, it will be worth to integrate your parser only if performance gains are really big and cannot be applied to ReplayParser.

**Comment by tobz** [comment]
Yup, makes sense.  I'll keep this issue updated as I continue progress and have more timings to share.

**Comment by poma** [comment]
Turns out Heroes.ReplayParser has a lot of room for improvement. Profiling shows that 60% time is spent decompressing bzip2 data. SharpZipLib that is used is very slow, switching it to sharpcompress already gives 2x improvement in decompression speed. But native implementation is at least 10x faster, trying to switch to that (although looks like it needs some wrapper).

A half of remaining time is spent in garbage collection in ReplayGameEvents.Parse, I think this also could be significantly optimized.

Overall, looks like ReplayParser can work 10x faster than it currently is.

**Comment by tobz** [comment]
Yeah, I mean, that's not terribly surprising.

Personally, I won't be helping to optimize Heroes.ReplayParser.  I'm not OK with Barrett's interactions with the community, and have no interest in helping him out for free when he's running a sketchy commercial venture. *shrug*

Totally understand if you'd rather optimize existing libraries instead of exploring using mine, but I'll be continuing with my work regardless.

I'll close this for now since it seems like you're leaning towards continuing Barrett's work.
