### ISSUE TITLE
Replays don't have the player list

### ISSUE THREAD

**Issue by masonk** [poma/hotsapi#64]
I might be misreading this, but the [api documentation ](http://hotsapi.net/docs) makes it look like the /replays endpoint should be returning a `players` array with 10 entries. However, when I "Try It Out", or when I use the [python library](https://github.com/MakiseKurisu/hotsapi), the players array is omitted from the response. Also, my response is truncated at 100 entries.

I am trying to build a corpus of metadata of games. I only want to pull down the following info for each game:

the 5 heroes on team 0
the 5 heroes on team 1
the map
who won

But I want to do it for all the replays. 

Is there more documentation somewhere that I should be reading?

**Comment by poma** [comment]
Documentation is currently incomplete. To include everything in replay list add `?with_players=1`. But this will pull all talents and scores (not parsed for most replays yet). You can also seed your database from [sql dump](https://s3-eu-west-1.amazonaws.com/poma/hotsapi.zip)

**Comment by masonk** [comment]
Thanks roma. I'll try that sql dump for now. It's perfect for getting started.

**Comment by poma** [comment]
docs updated
