### ISSUE TITLE
Site only responds without 'www' in the URL

### ISSUE THREAD

**Issue by ekzor** [poma/hotsapi#66]
no response: http://www.hotsapi.net/

functional: http://hotsapi.net/

this is something that needs to be set on the back end, either through your domain registrar or web host

**Comment by poma** [comment]
I just didn't add "www" record in DNS. Also I'm not sure that my SSL certificate will work (technically it's a subdomain and I don't have a wildcard cert).

What is the reason to add www anyway? I always thought it's a legacy practice and it's better to just drop it.

**Comment by ekzor** [comment]
you should be able to easily forward any requests to the 'www' to the version without so that the SSL cert works. as for the 'www' itself, i wouldn't say it's a legacy practice. automatic link parsing picks up on it, and many people will still type 'www' before a web address out of habit.

i actually opened this issue because i typed www.hotsapi.net in a reddit comment and someone responded saying it doesn't work (and i was too lazy to type 'http://' on my phone)

**Comment by poma** [comment]
> you should be able to easily forward any requests to the 'www' to the version without so that the SSL cert works

How does that work? SSL handshake is made before any HTTP requests so it encounders domain mismatch errors before it could ever receive a redirect. CNAME DNS enrty will not work for this too.

**Comment by ekzor** [comment]
my bad, you are absolutely correct. I think you are right about needing this as part of the SSL cert. Here's a resource I found: https://blog.dnsimple.com/2016/08/https-redirects/

**Comment by citricsquid** [comment]
Most certificate providers allow for you to secure both www and non-www with one certificate, meaning you do not need to purchase multiple certificates nor do you need a wildcard certificate, however, you cannot retroactively add an additional domain to a certificate. You will need to either purchase another certificate, or you could switch to a free certificate authority like [Let's Encrypt](https://letsencrypt.org). Paying for simple DV SSL certificates nowadays is unnecessary as Let's Encrypt provide everything you need.

The *ideal* configuration is one where all domains that a user might expect to exist, exist, and they redirect to your chosen domain, meaning you should pick one of the following and redirect the rest to your choice. 

- [ ] https://www.hotsapi.net
- [ ] https://hotsapi.net
- [ ] http://www.hotsapi.net
- [ ] http://hotsapi.net

There are some situations in which you need to allow your service to be accessible over http (legacy client access for example) but in most situations, you'd want to *only* provide your service over https for security.

**Comment by mjibson** [comment]
Another vote for Let's Encrypt. Some languages provide autocert packages that will automatically generate free certs for you (https://letsencrypt.org/docs/client-options/).

**Comment by vichle** [comment]
+1 for let's encrypt. It's super easy to set up, see:
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
or
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

**Comment by poma** [comment]
added redirect from www domain
