### ISSUE TITLE
Player talents return value

### ISSUE THREAD

**Issue by tbuehlmann** [poma/hotsapi#67]
When a player has talents, they are returned as an object:

```
"talents":{"1":"WitchDoctorWidowmakers","4":"WitchDoctorHexedCrawlers","7":"WitchDoctorSpiritofArachyr","10":"WitchDoctorHeroicAbilityRavenousSpirits","13":"GenericTalentIceBlock","16":"WitchDoctorSoulHarvest","20":"WitchDoctorVileInfection"}
```

When a player doesn't have talents, they are returned as an empty array:
```
"talents": []
```

Example replay: `https://hotsapi.net/api/v1/replays/7`

Shouldn't that be an empty object (or null)?

**Comment by poma** [comment]
I still need investigate closer why exactly [ReplayParser resets talents here](https://github.com/barrett777/Heroes.ReplayParser/blob/master/Heroes.ReplayParser/Statistics.cs#L232)

**Comment by koliva8245** [comment]
If you just want the talents, then use the `EndOfGameTalentChoices` event.
The `TalentChosen` event allows you to get the time at which the talent was chosen.

**Comment by tbuehlmann** [comment]
Great, thanks.
