### ISSUE TITLE
Add text sections to docs

### ISSUE THREAD

**Issue by poma** [poma/hotsapi#69]
Docs page needs to have a sections of static text in addition to swagger widget. We need separate pages to describe:

* General API info
* How to download, requester-pays bucket
* How to calculate replay checksum
* Path to sql dump and public bucket with images
* Links to ruby and python libs

**Comment by poma** [comment]
I'm not sure how to better design it. Probably a table of contents on top or to the side that switches between swagger docs and text pages.

**Comment by poma** [comment]
If someone helps to design menu I can then add all the content

**Comment by batosi175** [comment]
are you just looking for something like a markdown file?

**Comment by batosi175** [comment]
do you wanna do something like a summarized list on the side that persists. and just skip between sections using that?

**Comment by poma** [comment]
Probably something like [Laravel docs](https://laravel.com/docs) but flat (no subitems). But I also want it to not take away any space from Swagger docs, so I'm not entirely sure how to better design it.

**Comment by batosi175** [comment]
yea, I tend to like the subtle material feel. something sorta like this. keeping in mind I just pulled it from a random thing. 
![image](https://user-images.githubusercontent.com/9507793/31904244-517bace0-b7f0-11e7-9a00-439a58455e76.png)

**Comment by poma** [comment]
Looks good

**Comment by batosi175** [comment]
what do you use for the frontend on hotsapi.net?

**Comment by poma** [comment]
bootstrap, jquery, no other frameworks

**Comment by batosi175** [comment]
I'd love to help with the docs page. don't have a ton of experience with laravel or php (i come more from a react, ruby and ember brackground) but i'm willing to give it a shot if you'd like

**Comment by poma** [comment]
Backend doesn't matter much, I'll fix it if needed. I can't do frontend stuff well though so that's where help is needed the most.

**Comment by batosi175** [comment]
alright, i'll the repo tonight and help where I can

**Comment by MGatner** [comment]
Hey, following up on some of these "help wanted" issues. @batosi175 did you ever implement the menu for the docs frontend?

**Comment by MattdeGuehery** [comment]
I may be able to take a stab as this. Would tabs be an alternative? https://jqueryui.com/tabs/

Should be able to easily switch between api docs and static text docs as two tabs on top. Then static text could use accordions, a router of some kind for a SPA, or just exist on the page.

**Comment by poma** [comment]
I'm not sure how to fit tabs there while preserving a clean design? Can you make a screenshot or maybe draw a sketch in paint?

**Comment by poma** [comment]
just made separate pages
