### ISSUE TITLE
500 error at min_id=3853200

### ISSUE THREAD

**Issue by mjibson** [poma/hotsapi#71]
https://hotsapi.net/api/v1/replays?with_players=true&min_id=3853200

I get a 500 error at the above ID. The next block succeeds.

**Comment by mjibson** [comment]
There are games without hero names? That's going to be weird.

**Comment by poma** [comment]
Yes this happens when someone uploads a replay before hero name translation
is a available. I've decided that it's better to show all replays even when
some info is missing.

I have a task that rescans all broken replays regularly

**Comment by mjibson** [comment]
Here's why the decision to put incomplete data in the API may need to be rethought: users of your API (like me) now have to be aware of all of the kinds of things that might not be present in the API, and write to look for them and rescan the appropriate data. However these possibly missing things aren't documented anywhere, so the only way to know is be trial and error, which produces strange errors since they may not always be caught.

If you want to keep the API the same, I would request that you document the things that your rescanner might fix, so that your users are able to have a canonical list of things to check. But I would even more strongly encourage just not including partial data in the API. I'd way rather have only complete data even if it's late than incomplete data that I have to deal with. This allows update jobs to be idempotent, which is really nice.

Another option is to add an API to get games that have been rescanned since a certain date or rescan ID or something. This would allow for periodic querying of things to update.

Yet another option is to add an API that only returns completed games. The current APIs could remain unchanged, but with some new documented properties (that they may change over time). This new API would have to be indexed on something other than the replay ID since we would need to get them in the correct order, but that's fine.

**Comment by poma** [comment]
Agreed, Let's continue discussion in #72
