### ISSUE TITLE
id should be a numerical string, not a number; and is misidentifed

### ISSUE THREAD

**Issue by DavidJFelix** [poma/hotsapi#73]
This will probably be a marginally controversial bug report because of how pedantic it is, and I'm sorry in advance for that.

The first issue is: the api has the `id` field of all resources is marked as `int64`. Neither Javascript, nor JSON support int64 as a native type. JSON and Javascript use "Number" which is a float64 by [ECMA262 specification](https://www.ecma-international.org/ecma-262/5.1/#sec-8.5). This means that only 0 - 2^53 are representable integers. You can verify that there are unreachable numbers with this js:

```javascript
var a = Math.pow(2, 53)-1;
while true: {
   console.log(a);
   a += 1;
}
```

Notice how it doesn't count regularly. Those are ids which are unreachable. You may be able to represent them in JSON, because it's a string, but this is outside of the spec and could break some JSON serializers/deserializers. Now, you might be saying to me: 

> David that's billions of resources ahead of what we even have now and you're being pedantic.

Which might be partially true. But now is the time to fix it -- before people start storing your ids in numbers. Ids are not numbers. You don't do math on them anywhere but in the database when you do id + 1 to get the next id (I honestly also think you should randomize them, but that's beside the point here). Ids are computer names for things. Unfortunately, JSON isn't a super rich serialization format and names go in strings. Ids are strings. If they happen to be numerical, sequential, strings, that's fine. But they're strings, not numbers.

**Comment by poma** [comment]
That's just a documentation problem - swagger translates `integer` to `int64`. They actually all are unsigned int32.

**Comment by martijnhoekstra** [comment]
JSON is not specced by ECMA262, but by RFC7159. JSON numbers are specced as arbitrary precision: https://tools.ietf.org/html/rfc7159#page-6

**Comment by DavidJFelix** [comment]
@martijnhoekstra the spec specifically calls out the fact that integers can only be used to 2^53 range.

>  Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

But the point of this bug isn't to identify a limit of numbers, it's to point out that identifiers should always be strings. You don't get any of these issues with strings and it has the added benefit of allowing you to change your identifier sub-schema without changing your json schema. Say you go from numeric strings to UUID or decide that hero name is a fine identifier -- these all fit in the JSON string type.

Using JSON number for something you don't intend to do math on is always a mistake, that's the point being made here.

**Comment by DavidJFelix** [comment]
https://google.github.io/styleguide/jsoncstyleguide.xml#id
>Property Value Type: string

http://jsonapi.org/format/#document-resource-objects
>The values of the id and type members MUST be strings.

http://docs.couchdb.org/en/2.0.0/json-structure.html
>Requested document id string if it was specified or null otherwise.

And here's an example of how twitter is coping because they didn't simply make ID a string:
https://developer.twitter.com/en/docs/basics/twitter-ids

**Comment by poma** [comment]
> Using JSON number for something you don't intend to do math on is always a mistake, that's the point being made here.

When user knows that id is an integer and stores it as such it takes up less bytes in DB. I don't expect that we will ever have 10^18 replays.

> Say you go from numeric strings to UUID or decide that hero name is a fine identifier

In that case API consumers will need to alter their code anyway because id's of all existing objects will change. Also I doubt that we will ever make such breaking changes without a good reason.

**Comment by DavidJFelix** [comment]
> When user knows that id is an integer and stores it as such it takes up less bytes in DB. I don't expect that we will ever have 10^15 replays. In fact, we will never even cross int32 limits.

This is a false dichotomy. You can parse numeric strings as integers before storage if you know they adhere to such limits.

This is simply myopic. You're thinking of resources in the sense of replays, not events. There are thousands of events per game and you **could** give those unique identifiers so that more meaningful analysis can be done. Feel free to close this issue since you obviously think I'm wrong, but I'm telling you that transmitting id as a number is suboptimal. I've had to fix numerical ids at my past jobs on APIs.

**Comment by poma** [comment]
> You can parse numeric strings as integers before storage if you know they adhere to such limits.

What is the point of returning id as a string but promising that it is actually an integer?

> There are thousands of events per game and you could give those unique identifiers

In that case I can make event id a string type, but still have int ids for replays.

**Comment by DavidJFelix** [comment]
>What is the point of returning id as a string but promising that it is actually an integer?

**DON'T PROMISE THAT ITS AN INTEGER**

That's the whole point. Look at how free you are. You can now use numeric strings, uuids, names, words, base64 encoded longs, base64 encoded BigNumbers. It doesn't matter. You're leaking the abstraction that you use for the database to your users. Just because your database prefers numeric, linear indexes doesn't mean you need to impose api consumers to use numbers.

>In that case I can make event id a string type, but still have int ids for replays.

So you're saying that for this case, you're going to change the style, so you'll actually have 2 different types of identifiers. It boggles my mind how you can't see that this is a terrible opinion on style for an API and a huge code smell for consumers to simply not use it.

Also: 
> takes up less bytes in DB

This is insane. The cost of changing the byte size of your identifiers is inconsequential. A huge database will use less than 50MB of additional bytes by changing from sequential ints over to UUID and less than 1ms per transaction to generate those UUIDs. What's the benefit of non-sequential IDs?

Like I said at the beginning:

>This will probably be a marginally controversial bug report because of how pedantic it is, and I'm sorry in advance for that.

and predicted the response would be:

>David that's billions of resources ahead of what we even have now and you're being pedantic.

I hope you understand that I'm not trying to be an asshole, I just genuinely think that this is bad style and I care enough to tell you about it. I'm happy to simply go away and let you do whatever you feel is right -- you built it, not me. I'm just trying to share my experience creating and consuming extremely large APIs and passion for clean, consumable, RESTful apis. Also I don't like Hotslogs, so I want hotsapi to be good.

**Comment by poma** [comment]
I'm open to criticism and style suggestions, we have lots of issues in current API and need to take them all into account when designing API v2. But in this specific case it seems like overengineering to me, more abstractions is not always a good thing. Our ids are already numeric and even if we ever decide to change it we will need to expose new version of API because identifiers for old objects will change too.

> This is insane. The cost of changing the byte size of your identifiers is inconsequential. A huge database will use less than 50MB of additional bytes by changing from sequential ints over to UUID and less than 1ms per transaction to generate those UUIDs.

Even with current replay count it will use 300Mb per each additional byte in id fields. If we switch from int32 to uuid that's +10Gb in DB size or +25%. That's pretty significant (most of this is due to player_talent table)

**Comment by martijnhoekstra** [comment]
The advantages of making it a string are

* Json parsers that are unable to deserialize numbers that don't fit their
expected format will break is you do ever overflow
* You can serialize pretty much any datatype, including numbers to strings,
so if that ever happens you're covered.
* If you have other ids that aren't numbers, you can be consistent in your
data type
* Some style guides advocate strings, and it may discourage bike shedding

The disadvantages are

* you may have to customize serialization formats where you convert
integers in your DB to strings and back
* Your consumers will have to choose whether they interpret the string as a
number which may break if you change the format, or as a string, which is
much slower to compare and handle in general than the number represented by
the string

The only requirement of an identifier is that it uniquely identifies a
resource. Whether you identify them by strings of codepoints ("strings") or
strings of bits encoded as numbers.

A compromise could be to serialize to a double precision floating point
number which is a denser representation that is supported by json parsers
that don't properly handle arbitrary precision numbers, but there is
significant cognitive overhead there for the consumer in realizing that the
identifier is just an arbitrary encoding of a string of bits.


On Nov 2, 2017 17:01, "David J. Felix" <notifications@github.com> wrote:

UUID is an extreme that I'm not currently endorsing. I'm not even saying
that makes sense. Keep the scope of this ticket in mind. All I'm saying is
that ID *ought* to be a string in the json payload so that you can choose
to store it however you want on the backend. Ids are strings. I honestly
don't care if they're UUID/base64/whatever. I do think there is value in
non-sequential ids in many cases and that storage is literally the least
expensive resource in computing, but thats beside the point of this. The
point is not committing to something that is a bad idea.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/poma/hotsapi/issues/73#issuecomment-341470084>, or mute
the thread

**Comment by DavidJFelix** [comment]
> or as a string, which is
much slower to compare and handle in general than the number represented by
the string

I think everything else you said is spot on, @martijnhoekstra but I don't think this makes any sense. Thinking about string compares as "expensive" when the strings will all be shorter than 100 characters seems like over engineering. Technically, yes, they will take longer to compare. Perhaps even hundreds of times longer to compare. However, either integer or string compare will happen in nanosecond countable time and we're talking about networked database driven services which operate mostly with IO and relatively low CPU load. The main time cost is network, not CPU.

Further, there's a reason strings exist as an abstraction in languages these days rather than just binary packed registers and I'd argue that UTF-8 winning over bytestrings/ascii in new languages reinforces the fact that these tiny improvements to storage and compare for ids are not worth the cost to developer productivity and sanity.

**Comment by poma** [comment]
> The main time cost is network, not CPU.

In case of hotsapi it isn't. Network throughput is almost unlimited for cloud instances but CPU limit is hit pretty often (we have 0.5 CPU core on DB server). Also DB instances have way less RAM that they should have (1.5Gb for 40Gb database), so index size in bytes is very important.

Keep in mind that four our task I have to fit 300M row database + read replica + web server into $100/month so we can't just scale stuff like large companies do.

**Comment by DavidJFelix** [comment]
@poma Dude, I don't know how many times I have to explain this to you. You wouldn't even have to store the data differently in the database. You would see **zero** impact on the database with the change I'm proposing. @martijnhoekstra was talking about client code comparing the strings vs numbers. For you, its the same thing. Your PHP code takes the integer from the database and does a stringify for it. Your database is the same. The data is the same. The disk bits are the same. The JSON payload is different.

**Comment by poma** [comment]
Why would I replace more specific type with more general type if I'm not going to use any ids other than numeric ones? It just doesn't make any sense. The only arguments I've heard so far are:

* some parsers will break when id exceeds 2^53 (which will not happen)
* I could replace numeric ids with strings (which will not happen)
* someone said it's good

there is also an argument against it: 

* if I switch to strings other developers can't rely on it being integer and have to either add their own internal id or make it of string type in their db

So, so far I see no real reason to switch to strings

**Comment by DavidJFelix** [comment]
I don't really PHP, but as far as I can tell, the change would be something like:

https://github.com/poma/hotsapi/blob/master/app/Http/Resources/ReplayResource.php#L24
Here, where we would change to

```php
            'id' => (string) $this->id,
```

That's the scope that I'm talking about. Repeat on any resource which returns its own ID in the body. 

>Why would I replace more specific type with more general type

A string is **not** more general. The two are equally general. A more specific type would be an `Identifier` type which isn't defined yet, and I'll remind you integers are not. Integers happen to be enumerable, which is a valued attribute of identifiers. You would replace it with a string because you don't intend to do math on it and every mechanism for interacting with it benefits from it being a string. In fact, when you send it as a url (you know like `/heroes/1` ) you're sending it as a **string**. 

>* some parsers will break when id exceeds 2^53 (which will not happen)
* I could replace numeric ids with something else (which will not happen)

You can tell the future?

>* someone said it's good

Google. Twitter. I'm not trying to argue from authority. I have plenty of other reasons I think it's correct. But they definitely have done due diligence and now enforce this rule because of the problems I'm stating

> if I switch to strings other developers can't rely on it being integer and have to either add their own internal id or make it of string type in their db

To be fair, they can't rely on anything and why is a JSON service telling them how to store data in their database. They should either treat hotsapi as a source of truth and passthru to it or simply cache it as is... why would they store it?

> So, so far I see no real reason to switch to strings

That's fine. I said awhile ago it was and that I'd go away. But I still think it's wrong an a hallmark of an API I won't touch. I'm still unconvinced by your database storage problem. It's 2017, my bytes are playing tiny violins. I'll go now.

**Comment by tbuehlmann** [comment]
@DavidJFelix: I can see you're arguing with some kind of pathos, but I don't see the necessity. I agree that this really is pedantic and obviously a personal preference. If this really drives you bonkers, fork the project and change it, it's OSS after all.

I'm in for keeping the id to be an integer, it's perfectly fine. We also have "page-number"-pagination in place (ordered by id per default), I'm not sure I'd like to use strings for a page-number-pagination. Numbers make sense in this case.

**Comment by DavidJFelix** [comment]
There's a difference between id and page number. You do math on page numbers. Also the word "number" is in the name. However, it's still a string when it comes in on the URL, so you parse it into a number.

**Comment by tbuehlmann** [comment]
As we are talking about the external representation of the id, I don't get it "on the URL", I get it via JSON.

But you're right, the page number wasn't really what I was after. When filtering via min_id=42, that's a number and it wouldn't feel right being a string.
