### ISSUE TITLE
Question on POST /replays 

### ISSUE THREAD

**Issue by ajbdev** [poma/hotsapi#75]
The definition for the return value of the POST /replays route is defined as:

```
{
  "success": "string",
  "Error": "string",
  "status": "string",
  "id": 0,
  "file": "string",
  "url": "string"
}
```

What does the status string indicate? Is it a actually an enum? 
What is the string value of success? Is this actually a boolean?

What I am trying to figure out: are there any ways to indicate that a replay has already been uploaded?

**Comment by poma** [comment]
In case of duplicate it is `sucess: true, status: duplicate`. Currently response is not intuitive as outlined in #45 , we will improve it in the future. Generally success: true means that there was no server error during upload. status values are defined in [ParserService.php#L19](https://github.com/poma/hotsapi/blob/master/app/Services/ParserService.php#L19)

**Comment by ajbdev** [comment]
Ok. Will you be incrementing the API version then when that occurs? 

If I build it out as is and distribute my application to users and the signature of the return changes, my application will break for everyone who has downloaded it.

**Comment by poma** [comment]
No there will be no breaking changes for this endpoint. We will put reworked version on a different URL. Hotsapi uploader relies on it too.

**Comment by ajbdev** [comment]
Good to know, thank you. I will move forward with the existing API with confidence then :)
