### ISSUE TITLE
Replays by game_map

### ISSUE THREAD

**Issue by mlynam** [poma/hotsapi#78]
I notice in the API docs that the game_map query param is currently disabled. can we get a scope on this issue? I'd be willing to work on it given some requirements.

**Comment by poma** [comment]
Problem is a poor query performance. You can import SQL dump on your development server and try to optimize query execution times.

**Comment by mlynam** [comment]
Ok cool I can work on that.  I don't see a CONTRIBUTING.md file in the repo.  Do you have any PR requirements before I start working?

**Comment by poma** [comment]
Nope, no requirements

**Comment by mlynam** [comment]
Alright cool.  I'll probably write some integration / end-to-end tests and it is likely I'll use the query builder instead of eloquent to query replays.

**Comment by poma** [comment]
Just make sure that it will be easy extend your code in case we want to add more params in the future or alter resulting JSON in some way (I think you'll still need to convert result to eloquent object to use Resources for output)

**Comment by mlynam** [comment]
Ok I'll be sure to cover with tests.  I probably won't change your getQuery method, rather add a new method to use in index. If you are satisfied with the change it could be applied to the paged endpoint as well.

**Comment by mlynam** [comment]
And i'll be sensitive to extension efforts.

**Comment by mlynam** [comment]
where can I get my hands on a sqldump?

**Comment by poma** [comment]
http://s3.hotsapi.net/hotsapi.sql.gz

**Comment by poma** [comment]
Import may take quite a while on lower end servers. I plan to make .csv export for larger tables to speed up the process, I think I'll get to it in a couple of days.

**Comment by mlynam** [comment]
Lol, this is crushing my VM

**Comment by mlynam** [comment]
So the import slowdown is also impacted by constraints, like indexes (especially unique ones). If we were to strip the constraints before the import, blast all the data in, and then reattach the constraints, it would probably import way faster.

**Comment by poma** [comment]
That's what I did when I was migrating DB server from AWS to Google Cloud, coupled with loading large tables from .csv. But it doesn't help much - data import becomes indeed quite fast but rebuilding indexes and constraints takes forever (almost 10x longer than import) so the resulting import time is still almost the same - it took around 6 hours to import 3M replays.

**Comment by mlynam** [comment]
Understood. My VM is probably pretty underpowered for this import. It is still going.. 15 hours later.

**Comment by mlynam** [comment]
Still choking on the player_talent table which is of course locked so I can't get a count on it.

**Comment by poma** [comment]
That's the biggest table with 300M rows. You can get row count approximation from information_schema.tables

**Comment by mlynam** [comment]
Ah thanks. 176M so far.

**Comment by poma** [comment]
By the way, hotsapi production server is also pretty underpowered - 1.5Gb RAM and 0.5 CPU. Though on import I had a bit larger instance with 4 (or 2) CPUs.

**Comment by mlynam** [comment]
What version of mysql is it running?

**Comment by mlynam** [comment]
Or is that on a google server now?

**Comment by poma** [comment]
MySQL 5.7, yes currently on Google Cloud SQL

**Comment by MGatner** [comment]
@mlynam Did you ever get anywhere on this?

**Comment by poma** [comment]
I think this query will be deprecated once BigQuery dataset will become available, closing for now
