### ISSUE TITLE
Bans Missing post 2.28.5.59239

### ISSUE THREAD

**Issue by danewfie** [poma/hotsapi#85]
No games include Bans after Build 59239

Or am I missing something?

**Comment by Zemill** [comment]
From what I can tell, any games after 11/22 is missing most of the data.

I think there is an issue with the replay parser.  A workaround was created by Matt Jibson, you can find a link if you join the hotsapi gitter, but I am not sure I want to go that route.

Roman, 
What is the plan for resolving this?  Are you going to rebuild those replays in the DB once we get a working replay parser?

**Comment by poma** [comment]
yes, extended parsing sometimes lags behind (and was disabled some time ago) but eventually it catches up. The work around for now is to parse files yourself.
