### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by cuevasclemente** [poma/hotsapi#86]
Hi,

I wonder if there isn't some way to implement the functionality to export all replays in the database, maybe as a sql export. Right now trying to get all replays via `GET` commands would take a very long time while trying to avoid rate limiting.

**Comment by poma** [comment]
http://s3.hotsapi.net/hotsapi.sql.gz

I plan to implement a regular export to .csv (for faster loading)

Also I plan to insert everything into BigQuery so users will be able to query and export stuff very quickly.

**Comment by ncarlson** [comment]
Could we possibly get a more recent sql export? If not sql, a csv or BigQuery table will work.

Many thanks

**Comment by ncarlson** [comment]
> 
> 
> use http://s3.hotsapi.net/hotsapi.sql.gz as initial seed
> 
> I plan to implement a regular export to .csv (for faster loading)
> 
> Also I plan to insert everything into BigQuery so users will be able to query and export stuff very quickly.

Would you be willing to release a more up-to-date export of the seed database? If there's a lack of resources/time/money, I'm happy to help.

**Comment by poma** [comment]
now .csv dumps are updated daily

**Comment by ncarlson** [comment]
Thank you!

For reference, links to the CSV dumps are in the docs @ [hotsapi.net/docs](https://hotsapi.net/docs).
