### ISSUE TITLE
Return player region in API results

### ISSUE THREAD

**Issue by fheft** [poma/hotsapi#89]
Right now the API only returns the 'blizz_id' in a player object.
The BlizzardId (Battle.Net ID) is only unique within a (Battle.Net) region, so this ID on its own is useless.
I'd suggest returning the 'region' as well.

**Comment by poma** [comment]
We decided to more region into Replay object since it's the same for all players within a single replay

**Comment by fheft** [comment]
Oh I see, totally missed that. Thanks!
