### ISSUE TITLE
Responses cutoff midstream in Node

### ISSUE THREAD

**Issue by heroes-coding** [poma/hotsapi#90]
So, this is a new issue as of the last 24 hours.  Any get method in Node (I have tried the standard http.get and build up a response string or buffer, request, and axios modules, and all result in the same problem) gets cutoff in the middle somewhere, giving me an incomplete response to parse into JSON.  For an example (the request and axios code is simpler), here is the http.get code:

```
const http = require('http') ;
var requestURL = `http://hotsapi.net/api/v1/replays?with_players=true&min_id=5991976`
http.get(requestURL , function (resp) {
    var respContent = '';
    //let responseBuffer = new Buffer ([]);
    resp.on('data' , function (data) {
        respContent += data.toString();
        //responseBuffer = Buffer.concat([responseBuffer,data]);
    });
    resp.on('end' ,  function() {
        console.log(respContent,`Length of response: ${respContent.length}`);
        let response = JSON.parse(respContent)
    }) ;
}).on('error' , console.error);
```

This results in a response length of 78890, whether measured in characters or in the length of the response buffer, for any valid min_id above.  

It's the same for the request module or axios module, for example:

```
axios.get(requestURL).then(response => {
    const resp = response.data
    console.log(resp.length)
    let responseJSON = JSON.parse(resp)
  }).catch(error => { console.log(error)})
```

This results in the same length, 78890, as above.
Both of these modules automatically get all chunks of data before passing them to the response callback.  

On my home computer, the same code results in differing response length, but the same problem.

I can get the entire response in the browser, or curl, or in Python at least (not sure about other languages), so I guess I will use Python as a subprocess to pass back in the data, but perhaps there is something you just recently changed in the way responses are sent back?

**Comment by hypersad** [comment]
@heroes-coding is this problem still actual? I've tried your way and got `431666` response length.

**Comment by heroes-coding** [comment]
I'm not sure - I switched to a Python subprocess that works.

**Comment by poma** [comment]
looks like the problem is not actual. If someone else it having it feel free to reopen
