### ISSUE TITLE
Score Data and full Battletag Missing from HOTSAPI - Starting approximately 11/15/2017

### ISSUE THREAD

**Issue by Zemill** [poma/hotsapi#91]
I could not find a duplicate issue on this, but it appears that score data and full battletag is missing from the replays after 11/15/2017, or replay id 4866885.

I am using that data extensively for a website I will be releasing soon and was taking a look at the data for this Hero League season and wasn't finding much data.  I found that since 11/15/2017, there have been 330k replays uploaded without score data.

This is a pretty significant issue for my project and will pretty much make it useless.

Oddly enough, I have a few games where there is score data for hanzo games, which doesn't really make sense.  Replay ID 5704382  for example.  So something was fixed?  And then it was broken again?

**Comment by Zemill** [comment]
I can provide a listing of replay IDs that need re-run if we can come up with a fix.

I tried the workaround by Matt Jibson and it doesn't give all the information correctly.  So I am currently at a no-go with releasing my site...at least if I want to release something that has data for the Alex patch and on.

**Comment by Zemill** [comment]
Is this issue being looked into?  Beyond just score data and battletag data missing, talent data is missing.  So all we are really getting is whether a hero was played, and if they won.  This isn't really all that useful.  

The last message sent was that the heroprotocal repo hadn't been updated.  I looked at that repo, and it was updated 7 hours ago (likely due to blaze patch....).  I took a look at the latest replays in HOTSAPI, and its still missing data.

I do not see the point in continuing to import data into HOTSAPI in the state the API is right now.  As a player of the game, why would I want to send my replays to the API if it doesn't actually do anything.  As a supporter through patreon, why would I want to continue to support the API.

**Comment by enicn** [comment]
http://hotsapi.net/api/v1/replays?min_id=1337&start_date=2017-09-18&end_date=2018-09-30&game_type=HeroLeague&player=K1rk&with_players=true

I got a similar situation here. The link above that I uploaded my replay is lack of score data.

**Comment by maximtiourin** [comment]
HotsApi does secondary processing of replays separate from the initial replay upload processing, because parsing the replay for things like talents takes much more CPU than just getting the basic header. The "processed" flag is what will tell you if that specific replay has had secondary processing done on it yet. 

If you need replays fully parsed at your own desired rate, you need to use HotsApi as a replay repository, download the replays, and do all parsing yourself.

**Comment by Zemill** [comment]
Alright,

Thanks for the information.  I see that new replays are processing.  Old ones in the DB are still there not processed...so not sure what to make of that yet, I'll just have to put in a loop back to see if those have updated yet....
