### ISSUE TITLE
Confussing properties of replays.

### ISSUE THREAD

**Issue by enicn** [poma/hotsapi#93]
What dose "town_kills" mean? And "time_cc_enemy_heroes"?
What does "creep damage" and "minion damage" mean when they show up together?
Is there any manuel of replay's properties that I can refer to?

**Comment by poma** [comment]
They are taken as is from Heroes.ReplayParser which in turn are likely
taken from Blizzard's variable names. You can start by looking at
Heroes.ReplayParser code for descriptions.

**Comment by enicn** [comment]
Thanks for reply! I'll go check this out.
