### ISSUE TITLE
/Heroes API call returns 2 identical Hanzo objects.

### ISSUE THREAD

**Issue by Code47X** [poma/hotsapi#97]
The data just needs to be cleaned up a bit. 

I'm building out a component in React with the following line:

    {this.state.heroes.map(hero => <Hero key={hero.attribute_id} hero={hero} />)}

As you can see hero.attribute_id returned by your api is being used as my key. This will break because there are 2 nearly identical Hanzo records with the same attribute_id. Please combine these into one entry like all the other heroes.

**Comment by poma** [comment]
fixed
